server:
  port: ${port:8093}

logging:
  level:
    root: ${loglevel:INFO}
    #DEBUG

spring:
  kafka:
    listener:
      concurrency: 1
    consumer:
      properties:
        bootstrap.servers: 20.192.24.194:39092 #FYNDNA KAFKA
        auto.offset.reset: earliest
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group.id: neft-il-consumer
    producer:
      properties:
        bootstrap.servers: 20.192.24.194:39092 #FYNDNA KAFKA
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: org.apache.kafka.common.serialization.StringSerializer
        enable.auto.commit: false
        missing.topics.fatal: false
  # -------------------------------
  # R2DBC PostgreSQL Config
  # -------------------------------
  r2dbc:
    url: r2dbc:postgresql://34.135.239.235:5432/postgresdb
    username: admin
    password: test123
    pool:
      initial-size: 5
      max-size: 20
  #datasource:
    #url: ${DATABASE_URL:jdbc:postgresql://34.135.239.235:5432/postgresdb}
    #username: ${DATABASE_USERNAME:admin}
    #password: ${DATABASE_PWD:test123}
    #driver-class-name: ${DATABASE_DRIVERCLASS:org.postgresql.Driver}


file-type:
  processor:
    pacs.008.001.09: pacs008Processor
    pacs.004.001.10: pacs004Processor
    pacs.002.001.11: pacs002Processor
    camt.052.001.08: camt5254Processor
    camt.054.001.08: camt5254Processor
    camt.059.001.06: camt59Processor
    admi.004.001.01: admi004Processor
    admi.004.001.02: admi004Processor

  topic:
    pacs008Processor: neftil-pacs008-topic
    pacs004Processor: neftil-pacs004-topic
    pacs002Processor: neftil-pacs002-topic
    camt5254Processor: neftil-camt5254-topic
    camt59Processor: neftil-camt59-topic
    admi004Processor: neftil-admi004-topic

  xpaths:
    pacs.008.001.09: "(.//*[local-name()='RmtInf']//*[local-name()='Ustrd'])[1]"
    pacs.004.001.10: "(.//*[local-name()='RmtInf']//*[local-name()='Ustrd'])[1]"
    pacs.002.001.11: "(.//*[local-name()='StsRsnInf']//*[local-name()='AddtlInf'])[1]"
    camt.052.001.08: ".//*[local-name()='GrpHdr']//*[local-name()='AddtlInf']"
    camt.054.001.08: ".//*[local-name()='GrpHdr']//*[local-name()='AddtlInf']"

# -------------------------------
# Bypass Strategy Config
# -------------------------------
bypass:
  enabled: false                 # Enable/disable bypass globally
  default-switch: FC            # Default switch if not specified
  switches:
    FC: fc-kafka-topic          # Switch FC maps to this Kafka topic
    EPH: eph-kafka-topic        # Switch EPH maps to this Kafka topic

# -------------------------------
# Allowed Message Types for Batch Tracker
# -------------------------------
batch-tracker:
  allowedMsgTypes:
    - pacs.008.001.09
    - pacs.002.001.11
    - camt.054.001.08

# -------------------------------
# Exception Topic & Invalid msg default switch and topic
# -------------------------------
kafka:
  exception-topic: exception-topic
  default-invalid-msg-switch: FC
  default-invalid-msg-topic: fc-kafka-topic






